name: Build and Release PDF from LaTeX

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: paulhatch/semantic-version@v5.0.2
        id: vnum
        with:
          tag_prefix: ""
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}-${increment}"
          bump_each_commit: true
    
      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.vnum.outputs.version_tag }}
          message: Autorelease of PDF due to commit in main branch
      
      - name: Cleanup Directory
        run: rm -rf ./* 

      - name: Sleep Action
        uses: juliangruber/sleep-action@v2.0.0
        with:
          time: "30s"
    
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Release Tag
        uses: Akryum/release-tag@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vnum.outputs.version_tag }}
          release_name: Release ${{ steps.vnum.outputs.version_tag }}
          prerelease: false

      - name: Compile LaTeX document
        uses: Sakul6499/GitHub-Action-LaTeX@v0.0.1
        with:
          latex_main_file: resume.tex
          
      - name: Upload Resume PDF as Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: resume-nickorlow
          path: ./resume.pdf
          retention-days: 31
    
      - name: Release Resume PDF
        uses: djnicholson/release-action@v2.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag-name: ${{ steps.vnum.outputs.version_tag }}
          file: resume.pdf
          asset-name: "resume-nickorlow.pdf"

      - name: GitHub Upload Release Artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          created_tag: ${{ steps.vnum.outputs.version_tag }}
          






      
